# Generated by Django 5.1.4 on 2025-01-14 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_affiliations', models.TextField(blank=True, help_text='Community/communities the user identifies with.', null=True)),
                ('favorite_things', models.TextField(blank=True, help_text='Top three things the user likes about Yellowknife.', null=True)),
                ('community_insights', models.TextField(blank=True, help_text='What the user feels is important for other Yellowknifers to know about their community.', null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='profiles.profile')),
            ],
        ),
    ]
